<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{3ebd620b-e13f-4b0f-ae9c-4d4dc7ae0974}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	i:UDINT;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="19" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>