<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PG_SaveData" Id="{62c174cb-6994-498a-a2d1-50bf0c0b0a87}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PG_SaveData
VAR
	i:UDINT;
	k:UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
GVL.fbDataFlowManagement();]]></ST>
    </Implementation>
    <LineIds Name="PG_SaveData">
      <LineId Id="243" Count="0" />
      <LineId Id="270" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>